apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploydb
  namespace: lab3
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db
        image: '311335618943.dkr.ecr.us-east-1.amazonaws.com/amehta63-db:v1.0'
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : pw
        - name: DBPORT
          value : "3306"
        ports: 
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
        - mountPath: /tmp
          name: mysql-pvc
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
