apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-hp
  namespace: lab3
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mysql
  strorageClassName: localstorage