apiVersion: v1
kind: Service
metadata:
  name: lbwapp
  namespace: lab3
  labels:
    app: employees
    
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer